import { Senator } from './senator';

export const SENATORS: Senator[] = [
  {  id:1, name:"Marco Rubio", party:"Republican", state:"Florida"},
  {  id:2, name:"Rick Scott", party:"Republican", state:"Florida"},
  {  id:3, name:"Alexander Lamar", party:"Republican", state:"Tennesee"},
  {  id:4, name:"Tammy Baldwin", party:"Democrat", state:"Wisconsin"},
  {  id:5, name:"John Barrasso", party:"Republican", state:"Wyoming"},
  {  id:6, name:"Michael Bennet", party:"Democrat", state:"Colorado"},
  {  id:7, name:"Marsha Blackburn", party:"Republican", state:"Tennesee"},
  {  id:8, name:"Roy Blunt", party:"Republican", state:"Missouri"},
  {  id:9, name:"Richard Blumenthal", party:"Democrat", state:"Conneticut"},
  {  id:10, name:"Corey Booker", party:"Democrat", state:"New Jersey"},
  {  id:11, name:"John Boozman", party:"Republican", state:"Arkanas"},
  {  id:12, name:"Mike Braun", party:"Republican", state:"Indiana"},
  {  id:13, name:"Sherrod Brown", party:"Democrat", state:"Ohio"},
  {  id:14, name:"Richard Burr", party:"Republican", state:"North Carolina"},
  {  id:15, name:"Maria Cantwell", party:"Democrat", state:"Washington"},
  {  id:16, name:"Shelley Moore Capito", party:"Republican", state:"West Virginia"},
  {  id:17, name:"Benjamin Cardin", party:"Democrat", state:"Maryland"},
  {  id:18, name:"Thomas Carper", party:"Democrat", state:"Deleware"},
  {  id:19, name:"Robert Casey", party:"Democrat", state:"Pennsylvania"},
  {  id:20, name:"Bill Cassidy", party:"Republican", state:"Lousiana"},
  {  id:21, name:"Susan Collins", party:"Republican", state:"Maine"},
  {  id:22, name:"Christopher Coons", party:"Democrat", state:"Deleware"},
  {  id:23, name:"John Cornyn", party:"Republican", state:"Texas"},
  {  id:24, name:"Catherine Cortez Masto", party:"Democrat", state:"Nevada"},
  {  id:25, name:"Tom Cotton", party:"Republican", state:"Arkansas"},
  {  id:26, name:"Kevin Cramer", party:"Republican", state:"North Dakota"},
  {  id:27, name:"Mike Crapo", party:"Republican", state:"Idaho"},
  {  id:28, name:"Ted Cruz", party:"Republican", state:"Texas"},
  {  id:29, name:"Steve Daines", party:"Republican", state:"Montana"},
  {  id:30, name:"Tammy Duckworth", party:"Democrat", state:"Illinois"},
  {  id:31, name:"Richard Durbin", party:"Democrat", state:"Illinois"},
  {  id:32, name:"Michael Enzi", party:"Republican", state:"Wyoming"},
  {  id:33, name:"Joni Ernst", party:"Republican", state:"Iowa"},
  {  id:34, name:"Dianne Feinstein", party:"Democrat", state:"California"},
  {  id:35, name:"Deb Fischer", party:"Republican", state:"Nebraska"},
  {  id:36, name:"Corey Gardner", party:"Republican", state:"Colorado"},
  {  id:37, name:"Kirsten Gillibrand", party:"Democrat", state:"New York"},
  {  id:38, name:"Lindsey Graham", party:"Republican", state:"South Carolina"},
  {  id:39, name:"Chuck Grassley", party:"Republican", state:"Iowa"},
  {  id:40, name:"Kamala Harris", party:"Democrat", state:"California"},
  {  id:41, name:"Margaret Wood Hassan", party:"Democrat", state:"New Hampshire"},
  {  id:42, name:"Josh Hawley", party:"Republican", state:"Missouri"},
  {  id:43, name:"Martin Heinrich", party:"Democrat", state:"New Mexico"},
  {  id:44, name:"Mazie Hirono", party:"Democrat", state:"Hawaii"},
  {  id:45, name:"John Hoeven", party:"Republican", state:"North Dakota"},
  {  id:46, name:"Cindy Hyde-Smith", party:"Republican", state:"Mississippi"},
  {  id:47, name:"James Inhofe", party:"Republican", state:"Oklahoma"},
  {  id:48, name:"Ron Johnson", party:"Republican", state:"Wisconsin"},
  {  id:49, name:"Doug Jones", party:"Democrat", state:"Alabama"},
  {  id:50, name:"Tim Kaine", party:"Democrat", state:"West Virgina"},
  {  id:1, name:"Marco Rubio", party:"Republican", state:"Florida"},
];
