import { Senator } from './senator';

export const SENATORS: Senator[] = [
  {  id:1, name:"Marco Rubio", party:"Republican", state:"Florida"},
  {  id:2, name:"Rick Scott", party:"Republican", state:"Florida"},
  {  id:3, name:"Alexander Lamar", party:"Republican", state:"Tennesee"},
  {  id:4, name:"Tammy Baldwin", party:"Democrat", state:"Wisconsin"},
  {  id:5, name:"John Barrasso", party:"Republican", state:"Wyoming"},
  {  id:6, name:"Michael Bennet", party:"Democrat", state:"Colorado"},
  {  id:7, name:"Marsha Blackburn", party:"Republican", state:"Tennesee"},
  {  id:8, name:"Roy Blunt", party:"Republican", state:"Missouri"},
  {  id:9, name:"Richard Blumenthal", party:"Democrat", state:"Conneticut"},
  {  id:10, name:"Corey Booker", party:"Democrat", state:"New Jersey"},
  {  id:11, name:"John Boozman", party:"Republican", state:"Arkansas"},
  {  id:12, name:"Mike Braun", party:"Republican", state:"Indiana"},
  {  id:13, name:"Sherrod Brown", party:"Democrat", state:"Ohio"},
  {  id:14, name:"Richard Burr", party:"Republican", state:"North Carolina"},
  {  id:15, name:"Maria Cantwell", party:"Democrat", state:"Washington"},
  {  id:16, name:"Shelley Moore Capito", party:"Republican", state:"West Virginia"},
  {  id:17, name:"Benjamin Cardin", party:"Democrat", state:"Maryland"},
  {  id:18, name:"Thomas Carper", party:"Democrat", state:"Deleware"},
  {  id:19, name:"Robert Casey", party:"Democrat", state:"Pennsylvania"},
  {  id:20, name:"Bill Cassidy", party:"Republican", state:"Lousiana"},
  {  id:21, name:"Susan Collins", party:"Republican", state:"Maine"},
  {  id:22, name:"Christopher Coons", party:"Democrat", state:"Deleware"},
  {  id:23, name:"John Cornyn", party:"Republican", state:"Texas"},
  {  id:24, name:"Catherine Cortez Masto", party:"Democrat", state:"Nevada"},
  {  id:25, name:"Tom Cotton", party:"Republican", state:"Arkansas"},
  {  id:26, name:"Kevin Cramer", party:"Republican", state:"North Dakota"},
  {  id:27, name:"Mike Crapo", party:"Republican", state:"Idaho"},
  {  id:28, name:"Ted Cruz", party:"Republican", state:"Texas"},
  {  id:29, name:"Steve Daines", party:"Republican", state:"Montana"},
  {  id:30, name:"Tammy Duckworth", party:"Democrat", state:"Illinois"},
  {  id:31, name:"Richard Durbin", party:"Democrat", state:"Illinois"},
  {  id:32, name:"Michael Enzi", party:"Republican", state:"Wyoming"},
  {  id:33, name:"Joni Ernst", party:"Republican", state:"Iowa"},
  {  id:34, name:"Dianne Feinstein", party:"Democrat", state:"California"},
  {  id:35, name:"Deb Fischer", party:"Republican", state:"Nebraska"},
  {  id:36, name:"Corey Gardner", party:"Republican", state:"Colorado"},
  {  id:37, name:"Kirsten Gillibrand", party:"Democrat", state:"New York"},
  {  id:38, name:"Lindsey Graham", party:"Republican", state:"South Carolina"},
  {  id:39, name:"Chuck Grassley", party:"Republican", state:"Iowa"},
  {  id:40, name:"Kamala Harris", party:"Democrat", state:"California"},
  {  id:41, name:"Margaret Wood Hassan", party:"Democrat", state:"New Hampshire"},
  {  id:42, name:"Josh Hawley", party:"Republican", state:"Missouri"},
  {  id:43, name:"Martin Heinrich", party:"Democrat", state:"New Mexico"},
  {  id:44, name:"Mazie Hirono", party:"Democrat", state:"Hawaii"},
  {  id:45, name:"John Hoeven", party:"Republican", state:"North Dakota"},
  {  id:46, name:"Cindy Hyde-Smith", party:"Republican", state:"Mississippi"},
  {  id:47, name:"James Inhofe", party:"Republican", state:"Oklahoma"},
  {  id:48, name:"Ron Johnson", party:"Republican", state:"Wisconsin"},
  {  id:49, name:"Doug Jones", party:"Democrat", state:"Alabama"},
  {  id:50, name:"Tim Kaine", party:"Democrat", state:"West Virgina"},
  {  id:51, name:"John Kennedy", party:"Republican", state:"Louisiana"},
  {  id:52, name:"Angus King", party:"Independent", state:"Maine"},
  {  id:53, name:"Amy Klobuchar", party:"Democrat", state:"Minnesota"},
  {  id:54, name:"James Lankford", party:"Republican", state:"Oklahoma"},
  {  id:55, name:"Patrick Leahy", party:"Democrat", state:"Vermont"},
  {  id:56, name:"Mike Lee", party:"Republican", state:"Utah"},
  {  id:57, name:"Kelly Loeffler", party:"Republican", state:"Georgia"},
  {  id:58, name:"Joe Manchin", party:"Democrat", state:"West Virginia"},
  {  id:59, name:"Edward Markey", party:"Democrat", state:"Masseachusetts"},
  {  id:60, name:"Mitch McConnell", party:"Republican", state:"Kentucky"},
  {  id:61, name:"Martha McSally", party:"Republican", state:"Arizona"},
  {  id:62, name:"Robert Menendez", party:"Democrat", state:"New Jersey"},
  {  id:63, name:"Jeff Merkley", party:"Democrat", state:"Oregon"},
  {  id:64, name:"Jerry Moran", party:"Republican", state:"Kansas"},
  {  id:65, name:"Lisa Murkowski", party:"Republican", state:"Alaska"},
  {  id:66, name:"Christopher Murphy", party:"Democrat", state:"Conneticut"},
  {  id:67, name:"Patty Murray", party:"Democrat", state:"Washington"},
  {  id:68, name:"Rand Paul", party:"Republican", state:"Kentucky"},
  {  id:69, name:"David Perdue", party:"Republican", state:"Georgia"},
  {  id:70, name:"Gary Peters", party:"Democrat", state:"Michigan"},
  {  id:71, name:"Rob Portman", party:"Republican", state:"Ohio"},
  {  id:72, name:"Jack Reed", party:"Democrat", state:"Rhode Island"},
  {  id:73, name:"James Risch", party:"Republican", state:"Idaho"},
  {  id:74, name:"Pat Roberts", party:"Republican", state:"Kansas"},
  {  id:75, name:"Mitt Romney", party:"Republican", state:"Utah"},
  {  id:76, name:"Jacky Rosen", party:"Democrat", state:"Nevada"},
  {  id:77, name:"Mike Rounds", party:"Republican", state:"South Dakota"},
  {  id:78, name:"Bernard Sanders", party:"Independent", state:"Vermont"},
  {  id:79, name:"Ben Sasse", party:"Republican", state:"Nebraska"},
  {  id:80, name:"Brian Schatz", party:"Democrat", state:"Hawaii"},
  {  id:81, name:"Charles Schumer", party:"Democrat", state:"New York"},
  {  id:82, name:"Tim Scott", party:"Republican", state:"South Carolina"},
  {  id:83, name:"Jeanne Shaheen", party:"Democrat", state:"New Hampshire"},
  {  id:84, name:"Richard Shelby", party:"Republican", state:"Alabama"},
  {  id:85, name:"Kyrsten Sinema", party:"Democrat", state:"Arizona"},
  {  id:86, name:"Tina Smith", party:"Democrat", state:"Minnesota"},
  {  id:87, name:"Debbie Stabenow", party:"Democrat", state:"Michigan"},
  {  id:88, name:"Dan Sullivan", party:"Republican", state:"Alaska"},
  {  id:89, name:"Jon Tester", party:"Democrat", state:"Montana"},
  {  id:90, name:"John Thune", party:"Republican", state:"South Dakota"},
  {  id:91, name:"Thom Thillis", party:"Republican", state:"North Carolina"},
  {  id:92, name:"Patrick Toomey", party:"Republican", state:"Pennsylvania"},
  {  id:93, name:"Tom Udall", party:"Democrat", state:"New Mexico"},
  {  id:94, name:"Chris Van Hollen", party:"Democrat", state:"Maryland"},
  {  id:95, name:"Mark Warner", party:"Democrat", state:"Virgina"},
  {  id:96, name:"Elizabeth Warren", party:"Democrat", state:"Masseachusetts"},
  {  id:97, name:"Sheldon Whitehouse", party:"Democrat", state:"Rhode Island"},
  {  id:98, name:"Rodger Wicker", party:"Republican", state:"Mississippi"},
  {  id:99, name:"Ron Wyden", party:"Democrat", state:"Oregon"},
  {  id:100, name:"Todd Young", party:"Republican", state:"Indiana"}
  ];
